### ISSUE TITLE
_env.tpl checks for wrong db type when using Databricks 

### ISSUE THREAD

**Issue by maurice-freitag** [gadsme/charts#25]
When connecting to Databricks, `CUBEJS_DB_TYPE` should be set to `databricks-jdbc` as per the [Cube docs](https://cube.dev/docs/config/databases/databricks/jdbc). The [helper template](https://github.com/gadsme/charts/blob/main/charts/cube/templates/_env.tpl) checks for `databricks` however: 
```
{{- if eq $i.type "databricks" }}
{{- include "cube.env.database.databricks" (set $i "datasource" $e) }}
{{- end }}
```
Using `databricks` is of course not supported by Cube: 
```
Error: Unsupported db type: databricks
    at driverDependencies (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:24:9)
    at lookupDriverClass (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:36:23)
    at OptsHandler.getDriverConcurrency (/cube/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:276:48)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.queueOptions (/cube/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:311:34)
    at Function.getDriverMaxPool (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:79:31)
    at CubejsServerCore.resolveDriver (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:814:13)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:579:22
    at OrchestratorApi.testDriverConnection (/cube/node_modules/@cubejs-backend/server-core/src/core/OrchestratorApi.ts:206:24)
    at async Promise.all (index 0)
    at ApiGateway.readiness (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:2193:9)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/cached-handler.ts:58:9
```

**Comment by lvauvillier** [comment]
Thanks @maurice-freitag. PR Merged.
